name: CMake Linux GCC Clang

on: push

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        c_compiler: [gcc, clang]
        include:
          - os: ubuntu-latest
            cpp_compiler: g++
          - os: ubuntu-latest
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-dir=${{github.workspace}}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake 
        -B ${{steps.strings.outputs.build-dir}}
        -DCMAKE_CXX_COMPILER=${{matrix.cpp_compiler}}
        -S ${{steps.strings.outputs.build-dir}}

    - name: Build
      run: cmake --build ${{steps.strings.outputs.build-dir}}
